name: blogapp
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.2.5 
  shared_preferences: ^2.0.17 

  cupertino_icons: ^1.0.2
  cloud_firestore:
  flutter_bloc: ^8.1.1
  equatable: 
  get_it: ^7.2.0
  firebase_core: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  json_serializable:
  json_annotation:

flutter:

  uses-material-design: true

  assets:
    - asset/
    - asset/images/

  fonts:
    - family: Chivo
      fonts:
        - asset: asset/fonts/Chivo-Regular.ttf
        - asset: asset/fonts/Chivo-Black.ttf
        - asset: asset/fonts/Chivo-BlackItalic.ttf
        - asset: asset/fonts/Chivo-Bold.ttf
          weight: 700
        - asset: asset/fonts/Chivo-BoldItalic.ttf
        - asset: asset/fonts/Chivo-Italic.ttf
        - asset: asset/fonts/Chivo-Light.ttf
        - asset: asset/fonts/Chivo-LightItalic.ttf